on: pull_request
name: PR
jobs:
    oxlint:
        name: Lint JS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npx --yes oxlint@0.6.1 --deny-warnings # change to the latest release
